"""add_location_fields_to_farms

Revision ID: e6588038b774
Revises: 58d34dac68e7
Create Date: 2026-04-08 15:46:30.687796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6588038b774'
down_revision: Union[str, Sequence[str], None] = '58d34dac68e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('location_label', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('full_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'full_address')
    op.drop_column('farms', 'location_label')
    # ### end Alembic commands ###
